python1:
  build: .
  expose:
    - 80

python2:
  build: .
  expose:
    - 80

haproxy:
  image: hypriot/rpi-haproxy
  volumes:
   - ./haproxy:/haproxy-override
  links:
   - python1
   - python2
  ports:
   - "80:80"
   - "8080:8080"

  expose:
   - "80"
   - "8080"
